import { updateVoucher } from "./../pages/Voucher/voucher.reducer";
export const path = {
  login: "/login",
  register: "/register",
  home: "/",
  order: "/order",
  staff: "/staff",
  client: "/client",
  product: "/product",
  productDetail: "/product/detail/:id",
  updateProduct: "/product/update/:id",
  addnewProduct: "/product/addnew",
  productType: "/productType",
  voucher: "/voucher",
  voucherDetail: "/voucher/detail/:id",
  updateVoucher: "product/update/:id",
  detailOrder: '/order/detail/:orderId',
  createVoucher: "voucher/create",
  orderCancel: "/orderCancel",
};
